apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-email
    receivers:
      - uid: default-receiver
        type: webhook
        settings:
          url: http://127.0.0.1:1
        disableResolveMessage: true
