spring.datasource.url=jdbc:h2:file:${APP_PROD_ROOT:/tmp/midterm-production}/data/${APP_ENV:local}/midterm_prod_db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always
