spring.datasource.url=jdbc:postgresql://localhost:5432/spring_boot_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always

app.settings.pagination-limit=50
