spring.application.name=midterm

app.settings.title=Midterm Application
app.settings.pagination-limit=20
app.settings.contact-email=support@midterm.app

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always

spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
